# redleafd daemon sources makefile
# Originally written by Tirra <tirra.newly@gmail.com>
# (c) ReadLeaf team 2008

LIBDATA_OBJS=src/libdata/usrtc.o src/libdata/tree.o src/libdata/lslist.o \
	src/libdata/avl.o src/libdata/redblack.o src/libdata/splay.o




