# by tirra <tirra.newly@gmail.com> (c) 2006, 2007, 2008
# makefile for redleaf modulas sources

#CFLAGS+=-shared -nostartfiles

#cgi_modula: 
#	@echo "MD: cgi_modula.c"
#	@gcc ${CFLAGS} -I${INCLUDES} -o cgi_modula.so modulas/cgi_modula.c

#modules_clean:
#	@echo "RM: *.so modulas"
#	@rm -f *.so

